[workspace]
authors = ["Loic Gouarin <loic.gouarin@gmail.com>"]
channels = ["conda-forge"]
name = "euler"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
samurai = ">=0.26.1,<0.27"
cmake = ">=4.1.2,<5"
cxx-compiler = "1.10.*"
h5py = ">=3.14.0,<4"
matplotlib = ">=3.10.6,<4"
